### YamlMime:Lifecycle
metadata:
  title: Приложение за виртуализация на Microsoft 4.6 за настолни компютри Windows
  description: Microsoft Application Virtualization Hosting 4.6 за настолни компютри с Windows следва Фиксираните правила за жизнения цикъл.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Приложение за виртуализация на Microsoft 4.6 за настолни компютри Windows
summary: |+
  Microsoft Application Virtualization Hosting 4.6 за настолни компютри с Windows следва [Фиксираните](/lifecycle/policies/fixed) правила за жизнения цикъл.

  Това се отнася за следните издания: за настолни компютри с Windows

products:
  - windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
  - version: Service Pack 3
    startDate: 12/02/2013
    endDate: 07/14/2020
  - version: Service Pack 2
    startDate: 10/01/2012
    endDate: 01/13/2015
  - version: Service Pack 1
    startDate: 01/26/2011
    endDate: 10/08/2013
  - version: Original Release
    startDate: 05/27/2010
    endDate: 04/10/2012
content: |

  ## <a name="links"></a>Връзки 
  * [Информация за продукта и миграцията](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Правила за сервизните пакети](/lifecycle/policies/fixed#service-packs)

  > [!NOTE]
  > Тъй като клиентът App-V 4.6 използва App-V 4.5 Server, App-V 4.5 Server ще продължи да се поддържа спрямо жизнения цикъл на App-V 4.6, когато се използва с поддържания App-V 4.6 клиент.

  ## <a name="editions"></a>Издания 
  * за работен плот на Windows