### YamlMime:Lifecycle
metadata:
  title: 'Преглед на оригиналната статия на английски: 3111102'
  description: Виртуализация на Microsoft Приложения 5.1 следва фиксирани правила за жизнения цикъл.
  ms.date: 07/28/2020
  ms.openlocfilehash: 3f0cac2ee013dd73e44fe41d9ba1d07cfcfce2f1
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: bg-BG
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "848750"
name: 'Преглед на оригиналната статия на английски: 3111102'
summary: >+
  Виртуализация на Microsoft Приложения 5.1 следва [фиксирани](/lifecycle/policies/fixed) правила за жизнения цикъл.


  Това се отнася за следните издания: за услуги за отдалечен работен плот за windows настолни компютри

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Връзки \n* [Информация за продукта](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Издания \n* за услуги за отдалечен работен плот\n* за работни плотове на Windows"
