### YamlMime:Lifecycle
metadata:
  title: Защита за клиенти на Microsoft Forefront
  description: Защитата на клиенти на Microsoft Forefront следва правилата за фиксиран жизнен цикъл.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: bg-BG
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924244"
name: Защита за клиенти на Microsoft Forefront
summary: >+
  Защитата на клиенти на Microsoft Forefront следва правилата за [фиксиран](/lifecycle/policies/fixed) жизнен цикъл.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Връзки \n* [Защита на крайна точка на System Center](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Защитата на Forefront client е прекратена към 14 юли, 2015. Актуализациите на дефинициите за злонамерен софтуер и антиспайуер вече няма да са налични след края на поддръжката за версията на продукта. Моля, преценете защитата на крайна точка на System Center като заместител."
