### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: Microsoft Application Virtualization 5.1 следва Правилата за фиксиран жизнен цикъл.
  ms.date: 09/10/2020
  keywords: 'for Remote Desktop Services,for Windows Desktops'
name: Microsoft Application Virtualization 5.1
summary: |+
  Microsoft Application Virtualization 5.1 следва [Правилата](/lifecycle/policies/fixed) за фиксиран жизнен цикъл.

  Това се отнася за следните издания: за услуги за отдалечен работен плот, за Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Връзки 
  * [Информация за продукта](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)


  ## <a name="editions"></a>Издания 
  * за услуги за отдалечен работен плот
  * за работен плот на Windows